- name: create user
  user: name=kurasuta

- name: create directory
  file: path=/opt/kurasuta state=directory owner=kurasuta group=kurasuta

- name: create virtualenv and install dependencies
  become_user: kurasuta
  pip:
    name: "{{ item }}"
    virtualenv: /opt/kurasuta/.venv
    virtualenv_python: python3
  with_items:
    - requests

- name: copy script to get read arguments used in commands tracked by Sentry
  become_user: kurasuta
  template:
    src: templates/list-sentry-event-arguments.py
    dest: /opt/kurasuta/list-sentry-event-arguments.py
    mode: 0755
