- name: create user
  user: name=kurasuta

- name: create directory
  file: path=/opt/kurasuta state=directory owner=kurasuta group=kurasuta

- name: create virtualenv and install dependencies
  become_user: kurasuta
  pip:
    name: "{{ item }}"
    virtualenv: /opt/kurasuta/.venv
    virtualenv_python: python3
  with_items:
    - requests

- name: copy script to get read arguments used in commands tracked by Sentry
  template:
    src: templates/list-sentry-event-arguments.py
    dest: /opt/kurasuta/list-sentry-event-arguments.py
    owner: kurasuta
    mode: 0755

- name: create user
  user: name=backend_rest_api

- name: create directory
  file: path=/opt/Server state=directory owner=backend_rest_api group=backend_rest_api

- name: clone git repo
  become_user: backend_rest_api
  git: repo=https://github.com/Kurasuta/Server.git dest=/opt/Server force=yes

- name: python dependencies
  become_user: root
  pip:
    name: "{{ item }}"
    executable: pip3
  with_items:
    - flask
