---

- name: apply common configuration to all nodes
  hosts: all
  become: true
  become_user: root

  roles:
    - common

- name: deploy master node
  hosts: masters
  become: true
  become_user: root

  roles:
#    - postgres
    - kurasuta-master
#    - kurasuta-database
#    - sentry

- name: deploy worker nodes
  hosts: workers
  become: true
  become_user: root

  roles:
    - kurasuta-worker
