---

- name: apply common configuration to all nodes
  hosts: all
  become: true
  become_user: root

  roles:
    - common

- name: deploy master node
  hosts: masters
  become: true
  become_user: root

  roles:
    - postgres
    - kurasuta-master
    - kurasuta-database
    - sentry

- name: deploy satellite nodes
  hosts: satellites
  become: true
  become_user: root

  roles:
    - kurasuta-client
