- name: install dependencies
  become: true
  become_user: root
  apt: name={{ item }} state=present
  with_items:
    - python
    - python-pip
    - python-setuptools
    - python-dev
    - python-virtualenv
    - libxslt1-dev
    - gcc
    - libffi-dev
    - libjpeg-dev
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - libpq-dev
- name: install python dependencies
  become: true
  become_user: root
  pip: name=virtualenv
- name: create user
  become: true
  become_user: root
  user: name=sentry
- name: create directory
  become: true
  become_user: root
  file: path=/www/sentry state=directory owner=sentry group=sentry
- name: create virtualenv and install sentry
  become: true
  become_user: sentry
  pip:
    name: sentry
    virtualenv: /www/sentry
