- name: create database user
  become_user: postgres
  postgresql_user: name=worker password="{{ lookup('password', 'credentials/' + inventory_hostname + '/postgres_worker_password length=15') }}"

- name: create database
  become_user: postgres
  postgresql_db: name=kurasuta owner=worker
  register: db_created
