- name: install dependencies
  apt: name={{ item }} state=present
  with_items:
    - git
    - upx-ucl
    - p7zip
    - ssdeep
    - libffi-dev
    - libssl-dev
    - build-essential
    - python3
    - python3-dev
    - python3-pip
    - python3-ssdeep
    - python3-dateutil
    - python3-numpy
    - python3-setuptools
    - python3-magic
    - automake
    - autoconf
    - libtool
    - tmux

- name: create user
  user: name=worker uid=666

- name: create directory
  file: path=/opt/Worker state=directory owner=worker group=worker

- name: clone git repo
  become_user: worker
  git: repo=https://github.com/Kurasuta/Worker.git dest=/opt/Worker force=yes

- name: python dependencies 
  become_user: worker
  pip:
    name: "{{ item }}"
    executable: pip3
  with_items:
    - requests
    - pefile
    - raven
    - entropy
    - sdhash
    - nilsimsa
    - terminaltables

- name: configure raven client in Worker venv
  become_user: worker
  lineinfile: dest=/home/worker/.profile
              create=yes
              regexp="^export RAVEN_CLIENT_STRING="
              line='export RAVEN_CLIENT_STRING="{{ raven_client_string }}"'

- name: copy script to list running processes
  copy: 
    src: processes_running_at_least.py
    dest: /usr/local/bin/processes_running_at_least.py
    mode: 744

- name: copy script to send running processes to zabbix
  copy: 
    src: send-worker-number-to-zabbix 
    dest: /usr/local/bin/send-worker-number-to-zabbix 
    mode: 755

- name: create cronjob to kill long-running workers every minute
  cron:
    name: kill long running radare2 workers
    job: "/usr/local/bin/processes_running_at_least.py 300 | xargs -r kill"

- name: create cronjob to send worker number to zabbix
  cron:
    name: send worker number to zabbix
    minute: "*/10"
    job: "/usr/local/bin/send-worker-number-to-zabbix > /dev/null"
