- name: install usefull tools
  become: true
  become_user: root
  apt: name={{ item }} state=present
  with_items:
    - file
    - tree
    - unzip
    - htop
    - p7zip
    - p7zip-full
    - p7zip-rar
