- name: install dependencies
  apt: name={{ item }} state=present
  with_items:
    - git
    - upx-ucl
    - p7zip

- name: create user
  user: name=worker

- name: create directory
  file: path=/opt/Worker state=directory owner=worker group=worker

- name: clone git repo
  become_user: worker
  git: repo=https://github.com/Kurasuta/Worker.git dest=/opt/Worker

- name: create virtualenv and install sentry
  become_user: worker
  pip:
    name: "{{ item }}"
    virtualenv: /opt/Worker/.venv
  with_items:
    - pefile
    - raven
